# Generated by Django 2.2 on 2019-12-23 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 23, 8, 1, 0, 30180, tzinfo=utc), editable=False)),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2019, 12, 23, 8, 1, 0, 30220, tzinfo=utc))),
            ],
        ),
    ]
